
export const UPDATE_CODE = 'UPDATE_CODE'


export const TOGGLE_COMPACT_CODE = 'TOGGLE_COMPACT_CODE'
export const TOGGLE_SELF_DEFENDING = 'TOGGLE_SELF_DEFENDING'
export const TOGGLE_DISABLE_CONSOLE_OUTPUT = 'TOGGLE_DISABLE_CONSOLE_OUTPUT'

export const TOGGLE_DEBUG_PROTECTION = 'TOGGLE_DEBUG_PROTECTION'
export const TOGGLE_DEBUG_PROTECTION_INTERVAL = 'TOGGLE_DEBUG_PROTECTION_INTERVAL'

export const SET_SOURCEMAP_MODE = 'SET_SOURCEMAP_MODE'
export const SET_SOURCEMAP_BASE_URL = 'SET_SOURCEMAP_BASE_URL'
export const SET_SOURCEMAP_FILE_NAME = 'SET_SOURCEMAP_FILE_NAME'

export const SET_UNICODE_ARRAY_THRESHOLD = 'SET_UNICODE_ARRAY_THRESHOLD'
export const TOGGLE_ROTATE_UNICODE_ARRAY = 'TOGGLE_ROTATE_UNICODE_ARRAY'
export const TOGGLE_UNICODE_ARRAY = 'TOGGLE_UNICODE_ARRAY'
export const TOGGLE_WRAP_UNICODE_ARRAY_CALLS = 'TOGGLE_WRAP_UNICODE_ARRAY_CALLS'
export const TOGGLE_ENCODE_UNICODE_LITERALS = 'TOGGLE_ENCODE_UNICODE_LITERALS'

export const ADD_DOMAIN_LOCK = 'ADD_DOMAIN_LOCK'
export const REMOVE_DOMAIN_LOCK = 'REMOVE_DOMAIN_LOCK'

export const ADD_RESERVED_NAME = 'ADD_RESERVED_NAME'
export const REMOVE_RESERVED_NAME = 'REMOVE_RESERVED_NAME'
